name: readerkm
description: "Lectura de kilometraje y consumo de combustible, para dar gastos en viajes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  google_mlkit_text_recognition: ^0.12.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  http: ^1.5.0
  http_parser: ^4.0.2
  uuid: ^3.0.0
  path: ^1.8.3
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
